import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { FinalCta, PageHero, SectionIntro } from "@/components/site-shell";
import { pillars } from "@/lib/site-content";
import trainerImage from "@/assets/trainer-riding.jpg";
import heroImage from "@/assets/equestrian-hero.jpg";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [{ title: "Trainer & Philosophy | Titanium Equestrian" }, { name: "description", content: "Discover Titanium Equestrian's eventing-based philosophy: clear communication, correct foundations, and confident performance." }, { property: "og:title", content: "Trainer & Philosophy | Titanium Equestrian" }, { property: "og:description", content: "A disciplined, encouraging approach to developing horses and riders." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/about" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/about" }] }), component: AboutPage });

function AboutPage() {
  return <><PageHero eyebrow="Trainer & philosophy" title="Standards without shortcuts." copy="A thoughtful coaching approach where correct foundations, honest feedback, and respect for the horse drive every decision." image={heroImage} imageAlt="Eventing rider and horse confidently jumping a cross-country fence" />
    <section className="py-20 lg:py-32"><div className="site-container grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-start"><img src={trainerImage} alt="Titanium Equestrian trainer riding a bay horse in collected flatwork" width={1200} height={1408} loading="lazy" className="diagonal-image aspect-[4/5] w-full object-cover" /><div className="lg:pt-12"><SectionIntro eyebrow="The coach behind Titanium" title="Earn trust. Then build from it." /><p className="mt-8 text-lg leading-8">Titanium Equestrian was built around a simple conviction: progress should never come at the expense of understanding. The horse needs clarity. The rider needs tools they can carry forward. Both deserve a plan.</p><p className="mt-5 text-base leading-7 text-muted-foreground">The complete trainer name, founding story, competition history, certifications, and verified years of experience are ready to be added here once supplied. This page intentionally does not invent credentials.</p><div className="mt-9 border-l-2 border-primary bg-muted p-6"><p className="text-xs font-bold uppercase tracking-widest text-primary">Owner content needed</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Trainer name · qualifications · competition levels · notable mentors · founding year · teaching history</p></div></div></div></section>
    <section className="bg-muted py-20 lg:py-28"><div className="site-container"><SectionIntro eyebrow="A complete foundation" title="Three principles. One connected system." /><div className="mt-14 grid gap-px bg-border lg:grid-cols-3">{pillars.map(({ number, title, text }) => <article className="bg-background p-8" key={title}><span className="number-rule">{number}</span><h3 className="mt-14 font-display text-4xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{text}</p></article>)}</div><div className="mt-16 grid gap-12 lg:grid-cols-2"><div><h3 className="font-display text-4xl font-semibold">Why eventing?</h3><p className="mt-5 text-base leading-7 text-muted-foreground">Dressage develops balance, suppleness, and communication. Gymnastic jumping develops rhythm and technique. Cross-country education develops courage, adaptability, and judgement. Together, these skills create a more capable horse and a more complete rider—even when eventing is not the final destination.</p></div><div><h3 className="font-display text-4xl font-semibold">How progress is measured</h3><p className="mt-5 text-base leading-7 text-muted-foreground">Success is more than a ribbon. It can be a quieter transition, a rider making a better decision independently, a young horse understanding a new question, or a competition round that feels composed from beginning to end.</p></div></div></div></section>
    <section className="bg-secondary py-20 text-secondary-foreground lg:py-28"><div className="site-container grid gap-12 lg:grid-cols-[1fr_1fr] lg:items-center"><div><BadgeCheck className="h-10 w-10 text-primary" /><p className="eyebrow mt-8">Proudly sponsored</p><h2 className="mt-4 font-display text-5xl font-semibold sm:text-6xl">Antarès Sellier USA</h2></div><div><p className="text-xl leading-8">Sponsorship reflects a shared commitment to horsemanship, performance, and equipment built around the athlete.</p><p className="mt-5 text-sm leading-7 text-secondary-foreground/60">Titanium Equestrian is proud to be supported by Antarès Sellier USA, part of a globally respected French saddle-making tradition trusted across elite equestrian sport.</p><Button asChild className="mt-8"><Link to="/contact">Train with Titanium <ArrowRight /></Link></Button></div></div></section><FinalCta /></>;
}