import { createFileRoute, useSearch } from "@tanstack/react-router";
import { CheckCircle2, Facebook, Instagram, Phone } from "lucide-react";
import { useState, type FormEvent } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { SectionIntro } from "@/components/site-shell";
import { programs } from "@/lib/site-content";
import trainingImage from "@/assets/training-session.jpg";

const searchSchema = z.object({ program: z.string().optional() });
export const Route = createFileRoute("/contact")({ validateSearch: searchSchema, head: () => ({ meta: [{ title: "Book a Lesson | Titanium Equestrian" }, { name: "description", content: "Enquire about riding lessons, horse training, competition coaching, or clinics with Titanium Equestrian in Washington State." }, { property: "og:title", content: "Book a Lesson | Titanium Equestrian" }, { property: "og:description", content: "Start a conversation about your horse, experience, and goals." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/contact" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/contact" }] }), component: ContactPage });

function ContactPage() {
  const { program } = useSearch({ from: "/contact" });
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  return <section className="min-h-screen bg-muted pt-28 lg:pt-36"><div className="site-container grid overflow-hidden bg-background lg:grid-cols-[.78fr_1.22fr]"><aside className="relative min-h-[28rem] bg-secondary p-8 text-secondary-foreground sm:p-12 lg:min-h-[48rem]"><img src={trainingImage} alt="Focused equestrian lesson with trainer and rider" width={1408} height={1008} className="absolute inset-0 h-full w-full object-cover opacity-25" /><div className="relative flex h-full flex-col"><p className="eyebrow">Start the conversation</p><h1 className="mt-5 font-display text-5xl font-semibold leading-none sm:text-7xl">Your next ride starts here.</h1><p className="mt-6 max-w-md text-sm leading-7 text-secondary-foreground/70">Tell us where you are now and where you want to go. Titanium will follow up to confirm fit, availability, location, and the best training path.</p><div className="mt-auto pt-12"><a href="tel:+12532632021" className="flex items-center gap-3 text-xl font-semibold"><Phone className="h-5 w-5 text-primary" />+1 253-263-2021</a><p className="mt-4 text-sm text-secondary-foreground/60">Washington State · Pacific Northwest<br />Exact facility details provided during booking.</p><div className="mt-6 flex gap-3"><a href="#" className="social-link" aria-label="Facebook — link coming soon"><Facebook /></a><a href="#" className="social-link" aria-label="Instagram — link coming soon"><Instagram /></a></div></div></div></aside>
      <div className="p-8 sm:p-12 lg:p-16">{sent ? <div className="flex min-h-[34rem] flex-col justify-center"><CheckCircle2 className="h-12 w-12 text-primary" /><p className="eyebrow mt-8">Enquiry prepared</p><h2 className="mt-4 font-display text-5xl font-semibold">Thank you for reaching out.</h2><p className="mt-5 max-w-lg text-base leading-7 text-muted-foreground">This demonstration form is not connected to email yet. Your details were not sent or stored. Once a booking service is connected, enquiries can be delivered directly to Titanium Equestrian.</p><Button className="mt-8 w-fit" variant="dark" onClick={() => setSent(false)}>Send another enquiry</Button></div> : <><SectionIntro eyebrow="Book a lesson" title="Tell us about your goals." /><form className="mt-10 grid gap-5" onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-xs font-bold uppercase tracking-widest">Name<input className="field" name="name" required autoComplete="name" /></label><label className="grid gap-2 text-xs font-bold uppercase tracking-widest">Email<input className="field" type="email" name="email" required autoComplete="email" /></label></div><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-xs font-bold uppercase tracking-widest">Phone<input className="field" type="tel" name="phone" autoComplete="tel" /></label><label className="grid gap-2 text-xs font-bold uppercase tracking-widest">Program of interest<select className="field" name="program" defaultValue={program ?? ""} required><option value="" disabled>Select a program</option>{programs.map((item) => <option key={item.title}>{item.title}</option>)}</select></label></div><label className="grid gap-2 text-xs font-bold uppercase tracking-widest">Experience level<select className="field" name="experience" required><option value="" disabled>Select your level</option><option>New or returning rider</option><option>Developing rider</option><option>Competition focused</option><option>Horse owner seeking training</option><option>Barn or clinic host</option></select></label><label className="grid gap-2 text-xs font-bold uppercase tracking-widest">What would you like to work toward?<textarea className="field min-h-36 resize-y" name="message" required /></label><div className="grid gap-5 border-t border-border pt-6 sm:grid-cols-[1fr_auto] sm:items-center"><p className="text-xs leading-5 text-muted-foreground">Expect an initial reply with fit, scheduling, and next-step information. Response-time details will be added when confirmed.</p><Button type="submit" size="lg">Send enquiry</Button></div></form></>}</div></div></section>;
}