import { createFileRoute } from "@tanstack/react-router";
import { Quote } from "lucide-react";
import { FinalCta, PageHero, SectionIntro } from "@/components/site-shell";
import { resultTypes, sampleTestimonials } from "@/lib/site-content";
import crossCountryImage from "@/assets/cross-country.jpg";

export const Route = createFileRoute("/testimonials")({ head: () => ({ meta: [{ title: "Testimonials & Results | Titanium Equestrian" }, { name: "description", content: "See the kinds of rider confidence, horse development, and competition progress Titanium Equestrian is built to support." }, { property: "og:title", content: "Testimonials & Results | Titanium Equestrian" }, { property: "og:description", content: "Progress stories from Titanium Equestrian coaching and training." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/testimonials" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/testimonials" }] }), component: TestimonialsPage });

function TestimonialsPage() {
  return <><PageHero eyebrow="Testimonials & results" title="Progress you can feel." copy="The most meaningful results show up in clearer communication, stronger confidence, and performance that becomes repeatable." image={crossCountryImage} imageAlt="Horse and rider moving confidently through a cross-country water obstacle" />
    <section className="py-20 lg:py-28"><div className="site-container"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><SectionIntro eyebrow="Client experiences" title="Trust, translated into progress." /><p className="max-w-sm text-xs leading-6 text-muted-foreground">The stories below are sample layout copy and will be replaced with verified client words, names, and images before launch.</p></div><div className="mt-14 grid gap-px bg-border lg:grid-cols-3">{sampleTestimonials.map((item, index) => <blockquote key={item.detail} className={`bg-background p-8 ${index === 1 ? "lg:translate-y-8" : ""}`}><Quote className="h-7 w-7 text-primary" /><p className="mt-8 font-display text-2xl font-medium leading-snug">“{item.quote}”</p><footer className="mt-10 border-t border-border pt-5"><p className="text-sm font-bold">{item.name}</p><p className="mt-1 text-[.62rem] uppercase tracking-widest text-muted-foreground">{item.detail}</p></footer></blockquote>)}</div></div></section>
    <section className="bg-secondary py-20 text-secondary-foreground lg:py-28"><div className="site-container"><SectionIntro inverse eyebrow="What the work changes" title="Results beyond the scoreboard." /><div className="mt-14 grid gap-px bg-secondary-foreground/15 sm:grid-cols-3">{resultTypes.map(({ icon: Icon, value, label }) => <div key={label} className="bg-secondary p-8"><Icon className="h-7 w-7 text-primary" /><p className="mt-12 font-display text-5xl font-semibold">{value}</p><p className="mt-2 text-xs font-bold uppercase tracking-widest text-secondary-foreground/55">{label}</p></div>)}</div></div></section>
    <section className="py-20 lg:py-28"><div className="site-container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><SectionIntro eyebrow="Result framework" title="The milestones worth recording." /><div className="divide-y divide-border border-y border-border">{[["Horse development", "Improved balance, more consistent responses, confidence with new questions, and productive owner handover."],["Rider progress", "Stronger position, clearer aids, improved decision-making, and confidence rooted in repeatable skills."],["Competition readiness", "A preparation process that connects home training, warm-up strategy, course decisions, and post-event learning."]].map(([title,text],i)=><article key={title} className="grid grid-cols-[3rem_1fr] gap-4 py-7"><span className="text-xs font-bold text-primary">0{i+1}</span><div><h3 className="font-display text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></div></article>)}</div></div></section><FinalCta /></>;
}