import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, Play } from "lucide-react";
import { Button } from "@/components/ui/button";
import { FinalCta, PageHero, SectionIntro } from "@/components/site-shell";
import { programs } from "@/lib/site-content";
import trainingImage from "@/assets/training-session.jpg";
import crossCountryImage from "@/assets/cross-country.jpg";

export const Route = createFileRoute("/training-programs")({
  head: () => ({ meta: [{ title: "Training Programs & Riding Lessons | Titanium" }, { name: "description", content: "Explore private lessons, group coaching, horse training, competition support, and clinics from Titanium Equestrian." }, { property: "og:title", content: "Training Programs | Titanium Equestrian" }, { property: "og:description", content: "Eventing-based coaching programs for riders and horses in Washington State." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/training-programs" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/training-programs" }] }),
  component: ProgramsPage,
});

function ProgramsPage() {
  return <><PageHero eyebrow="Training programs & lessons" title="Purposeful work. Real progress." copy="Choose the pathway that fits your horse, your experience, and the performance goals you are ready to pursue." image={crossCountryImage} imageAlt="Eventing horse and rider galloping through a water complex" />
    <section className="py-20 lg:py-28"><div className="site-container"><SectionIntro eyebrow="Five ways to move forward" title="Built around the partnership—not a template." copy="Every enquiry begins with your current experience, horse, access, and goals. Program details below are a clear starting point; the final plan is tailored after a conversation." /><div className="mt-16 divide-y divide-border border-y border-border">{programs.map(({ id, number, title, category, forWho, includes, approach, price, icon: Icon }) => <article id={id} key={title} className="grid gap-8 py-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-16 lg:py-16"><div><span className="number-rule">{number}</span><Icon className="mt-12 h-8 w-8 text-primary" /><p className="mt-7 text-[.65rem] font-bold uppercase tracking-[.18em] text-primary">{category}</p><h2 className="mt-3 font-display text-4xl font-semibold leading-none sm:text-5xl">{title}</h2><p className="mt-5 text-sm font-semibold">{price}</p></div><div><p className="text-lg leading-8">{forWho}</p><div className="mt-8 grid gap-8 sm:grid-cols-2"><div><h3 className="text-xs font-bold uppercase tracking-widest">What’s included</h3><ul className="mt-4 grid gap-3">{includes.map((item) => <li key={item} className="flex gap-3 text-sm text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{item}</li>)}</ul></div><div><h3 className="text-xs font-bold uppercase tracking-widest">The eventing approach</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{approach}</p></div></div><Button asChild className="mt-9"><Link to="/contact" search={{ program: title }}>Enquire about this program <ArrowRight /></Link></Button></div></article>)}</div></div></section>
    <section className="bg-secondary py-20 text-secondary-foreground lg:py-28"><div className="site-container grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div className="relative"><img src={trainingImage} alt="Trainer guiding a rider through a gymnastic pole exercise" width={1408} height={1008} loading="lazy" className="aspect-video w-full object-cover opacity-80" /><div className="absolute inset-0 grid place-items-center"><span className="grid h-20 w-20 place-items-center rounded-full bg-primary text-primary-foreground"><Play className="ml-1 h-7 w-7" /></span></div><p className="absolute bottom-4 left-4 bg-secondary px-3 py-2 text-[.6rem] font-bold uppercase tracking-widest">Training film placeholder</p></div><SectionIntro inverse eyebrow="See the work" title="Teaching style matters." copy="A future training film will show the pace, communication, and progression inside real sessions—so prospective clients can understand the coaching before they commit." /></div></section>
    <section className="py-20 lg:py-28"><div className="site-container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><SectionIntro eyebrow="Practical details" title="Questions before your first ride." /><div className="divide-y divide-border border-y border-border">{[
      ["Do I need my own horse?", "Not necessarily. School-horse availability has not yet been confirmed; mention your needs in the enquiry form and Titanium will advise on the right option."],
      ["What levels do you teach?", "Programs are designed to support developing riders through competition-focused partnerships. Exact age, level, and suitability are confirmed during the initial conversation."],
      ["Where does training take place?", "Titanium Equestrian serves Washington State and the Pacific Northwest. The exact facility and off-site travel arrangements will be confirmed directly."],
      ["How do packages and scheduling work?", "Start with an enquiry. Titanium will discuss goals, availability, horse access, and the most suitable lesson or training cadence before confirming a booking."],
    ].map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-2xl font-semibold"><span>{question}</span><span className="text-primary transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">{answer}</p></details>)}</div></div></section><FinalCta /></>;
}